-- Stages that are not a partition.
--
-- Every reading in waves 1 to 4 rests on a shape: a subject occupies one stage at a time, moves forward,
-- and stops. That shape is what makes "reached stage k" a well-defined event, "the rate at stage k" a
-- fraction of a fixed denominator, and "the product of the pass rates" an upper bound nothing can exceed.
--
-- Real subjects break all three, and this file builds a second event log where they do. Same subjects, same
-- arrival days, same coins for the ordinary forward steps - so every difference between the two logs is a
-- movement the monotone model cannot represent, and nothing else.

-- Whether each subject skips, falls back and comes back, decided once and drawn from the declared streams.
CREATE OR REPLACE TABLE movement_draws AS
SELECT
    s.subject_id,
    s.funnel,
    s.cohort_day,
    passes(s.subject_id, 2003, m.skip_rate)     AS skips,
    passes(s.subject_id, 2237, m.reentry_rate)  AS would_return,
    m.fallback_rate
FROM subjects s
JOIN movements m ON m.funnel = s.funnel;

-- The walk, with three extra kinds of move.
--
-- One recursive term, because a recursive query may refer to itself once. The moves a state can make are
-- generated by a lateral: a forward step, a skip from step one straight to step three, or a fallback to the
-- step before. A fallback raises the attempt number, which switches the subject onto its second pair of
-- streams - without that, the way back up meets the coin that already sent it down and the return is
-- certain rather than uncertain.
-- Pass one: everybody starts on their cohort day.
CREATE OR REPLACE TABLE messy_entry_points AS
SELECT subject_id, funnel, 1 AS entry, cohort_day::DOUBLE AS starts_at FROM movement_draws;

CREATE OR REPLACE MACRO walk_forward(subject_id, step, salt, rate) AS passes(subject_id * 16 + step, salt, rate);

-- The walk of one entry, given where and when it starts and which pair of streams it draws from.
--
-- One recursive term, because a recursive query may refer to itself once. The moves a state can make are
-- generated by a lateral: an ordinary forward step, a skip from step one straight to step three, or a
-- fallback to the step before. A fallback raises the attempt number, which switches the subject onto its
-- second pair of streams - without that, the way back up meets the coin that already sent it down and the
-- return is certain rather than uncertain.
--
-- This is written once and run twice, because whether a subject comes back depends on how far its *first*
-- entry got, and a single recursion cannot both produce that answer and consume it. The first version of
-- this file conditioned the return on the monotone log of sql/20_events.sql instead, which was convenient
-- and wrong: a subject that skips its way to the end in the messy log would still have been sent back
-- because the monotone log says it failed. Defect 16.
CREATE OR REPLACE MACRO messy_entry(entry_number) AS TABLE
WITH RECURSIVE walk AS (
    SELECT
        e.subject_id, e.funnel, entry_number::INTEGER AS entry,
        1 AS step, 1 AS attempt, e.starts_at AS reached_day, FALSE AS fell_back,
        w.pass_salt, w.lag_salt
    FROM messy_entry_points e
    JOIN walk_salts w ON w.entry = entry_number AND w.attempt = 1
    WHERE e.entry = entry_number

    UNION ALL

    SELECT
        w.subject_id, w.funnel, w.entry, m.next_step, m.next_attempt, m.next_day, m.next_fell_back,
        n.pass_salt, n.lag_salt
    FROM walk w
    JOIN movement_draws d ON d.subject_id = w.subject_id,
    LATERAL (
        SELECT st.step AS next_step, w.attempt AS next_attempt, w.fell_back AS next_fell_back,
               w.reached_day + lag_days(w.subject_id * 16 + st.step, w.lag_salt, st.lag_mean_days) AS next_day
        FROM stages st
        WHERE st.funnel = w.funnel AND w.step = 1 AND d.skips AND st.step = 3
          AND walk_forward(w.subject_id, st.step, w.pass_salt, st.pass_rate)

        UNION ALL
        SELECT st.step, w.attempt, w.fell_back,
               w.reached_day + lag_days(w.subject_id * 16 + st.step, w.lag_salt, st.lag_mean_days)
        FROM stages st
        WHERE st.funnel = w.funnel AND st.step = w.step + 1
          AND NOT (w.step = 1 AND d.skips)
          AND walk_forward(w.subject_id, st.step, w.pass_salt, st.pass_rate)

        UNION ALL
        SELECT st.step, 2, TRUE,
               w.reached_day + lag_days(w.subject_id * 16 + w.step, 2417,
                   (SELECT value FROM movement_params WHERE key = 'fallback_delay_days'))
        FROM stages st
        WHERE st.funnel = w.funnel AND st.step = w.step - 1
          AND w.step >= 3 AND NOT w.fell_back
          AND passes(w.subject_id * 16 + w.step, 2111, d.fallback_rate)
    ) m
    JOIN walk_salts n ON n.entry = w.entry AND n.attempt = m.next_attempt
)
SELECT * FROM walk;

CREATE OR REPLACE TABLE messy_first AS SELECT * FROM messy_entry(1);

-- Pass two: the subjects whose first entry did not reach the last stage of their own funnel, and whose
-- return coin is up, start again after the declared wait.
CREATE OR REPLACE TABLE messy_entry_points AS
SELECT subject_id, funnel, 1 AS entry, cohort_day::DOUBLE AS starts_at FROM movement_draws
UNION ALL
SELECT
    d.subject_id, d.funnel, 2,
    f.finished_at + lag_days(d.subject_id, 2389,
        (SELECT value FROM movement_params WHERE key = 'reentry_delay_days'))
FROM movement_draws d
JOIN (
    SELECT subject_id, max(reached_day) AS finished_at, max(step) AS furthest
    FROM messy_first GROUP BY 1
) f ON f.subject_id = d.subject_id
JOIN (SELECT funnel, max(step) AS last_step FROM stages GROUP BY 1) l ON l.funnel = d.funnel
WHERE d.would_return AND f.furthest < l.last_step;

CREATE OR REPLACE TABLE messy_walk AS
WITH entries AS (SELECT * FROM messy_first UNION ALL SELECT * FROM messy_entry(2))
SELECT
    b.subject_id, b.funnel, b.entry, b.attempt, b.step, st.stage, b.fell_back,
    d.cohort_day, b.reached_day, b.reached_day - d.cohort_day AS age_at_stage,
    b.reached_day <= (SELECT value FROM params WHERE key = 'as_of_day') AS observed
FROM entries b
JOIN movement_draws d ON d.subject_id = b.subject_id
JOIN stages st ON st.funnel = b.funnel AND st.step = b.step;

CREATE OR REPLACE TABLE messy_events AS
SELECT * FROM messy_walk WHERE observed;
